--  Configuration for secure_redis_spark_allocator generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Secure_Redis_Spark_Allocator_Config is
   pragma Pure;

   Crate_Version : constant String := "0.1.0-dev";
   Crate_Name : constant String := "secure_redis_spark_allocator";

   Alire_Host_OS : constant String := "macos";

   Alire_Host_Arch : constant String := "aarch64";

   Alire_Host_Distro : constant String := "homebrew";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Secure_Redis_Spark_Allocator_Config;
